title: "Mariana Arboleda"
email: marianaarboleda@uninorte.edu.co
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Mariana
paginate: 30
disqus: 'marianaarboleda'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-81760CJSJH

# Authors
authors:
  mariana:
    name: Mariana Arboleda
    display_name: Mariana
    avatar: 'assets/images/sal.png'
    email: marianaarboleda@uninorte.edu.co
    twitter: https://twitter.com/marbolf/
    description: "PhD Student. Teacher"
  
# Social
social:
  instagram: https://www.instagram.com/mariaf494/
  twitter: https://twitter.com/marbolf

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives